backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
  - name: blog
    label: "Blog"
    folder: "pages/posts"
    create: true
    identifier_field: slug
    slug: "{{slug}}"
    summary: "{{summary}}"
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Summary", name: "summary", widget: "text", required: true}